### ISSUE TITLE
Core Tasks

### ISSUE THREAD

**Issue by drcynic** [still-scene/t3#1]
- [ ] When recompiling a composition op move the child instances of the old one to new one instead of recreating them.
- [ ] Remove the `Add` hack and add all operator types to `ResourceManager` and update the `Type` in their `Symbol` if the code got recompiled.
- [ ] Add general handling for loading operator source from external files
- [ ] Rename `OperatorTests` to `CoreTests`
- [ ] `ResourceManager` Ids should be just of type `int` instead of type `Guid`
- [x] Move logging to Core

**Comment by pixtur** [comment]
These tasks are outdated.
