### ISSUE TITLE
UI goes black when using a non-cubemap environment texture.

### ISSUE THREAD

**Issue by ScreenDream** [still-scene/t3#115]
The whole user interface of t3 goes 99.9% black if I connect a non-cubemap texture to the environment operator.
This doesn't create a crash but I haven't found a way to get out of this state, only restarting t3 works.
This happens in all versions of t3 I tried, from 3.3 standalone to the latest dev build of today.

Steps to reproduce:
Create a SetEnvironment operator.
Connect a texture2d with a frog to it. 
Click on the Environment node or hover over it with the mouse.
Enjoy the darkness :-)

See attached screenshot - if you turn up brightness, you can see some outlines of the nodes.

**Please complete the following information):**
 - OS: Windows
 - Version: Latest dev
 - Graphics card and resolution: Geforce GTX 840M, 2GB VRAM, 1920x1080 
 - Acer Laptop, 16 GB RAM. Windows 10.
 - All latest updates and drivers installed.

![t3_BlackScreenEnvironment](https://user-images.githubusercontent.com/113698935/191047126-af56c6a6-9a04-43ec-8d51-db8558417ed6.jpg)

**Comment by sense-amr** [comment]
this can easily be solved .. by following the input parameters required by SetEnvironment .. which is .. data type CubeMap 
![image](https://user-images.githubusercontent.com/1504019/191325705-962bb848-7b37-4ca7-ac84-ddd81ed2ba84.png)


which can easily be created by using the operator TextureToCubeMap2 .. which accepts a Texture2d input .. 
![image](https://user-images.githubusercontent.com/1504019/191325839-d89249f9-65a9-40e5-9e8f-133c8a1ca455.png)

**Comment by VeissieV** [comment]
It shouldn't bomb the application requiring a restart to continue. The solution is perhaps a message telling the user they need the TextureToCubeMap or the proper image format or just not working at all but allowing you to continue. I believe I've also encountered this whilst using the proper nodes but changing textures or possibly using a file that was 16bit or just not a format that Tooll supports. 

I didn't see documentation for SetEnvironment supported image formats but thought .DDS was probably ideal since it's what the default resource is. I haven't found a good way to convert .EXR and .HDR into a working .DDS file.

**Comment by sense-amr** [comment]
yeh everyone encountered it in super old unupdated versions .. but it does CLEARLY ask for a CubeMap ..

**Comment by ScreenDream** [comment]
The bug with the steps I reported above is still there in the latest dev version of today.
For me it is a bug if something brings an application into a state from which the user can't recover without closing and restarting the application.
Since other software like vvvv creates the cube map on the fly or at worst shows a wrong reflection, I   don't see why you go to such a length to deny the issue?

**Comment by pixtur** [comment]
I think this was a very annoying issue that happened frequently and required a fix.
In the upcoming version v3.4 [SetEnvironment] will check if the incoming texture format is cubemap and will print warning level if this this is not case:

![image](https://user-images.githubusercontent.com/1732545/191577551-8df3bf94-ce2b-433a-98a2-997f86405e26.png)

Although not a good as converting the texture on the fly, its a first fix to circumvent the black UI issue.

A better longer term approach would be to have a new [FallbackCubeTexture] operator that does the conversion automatically if the format doesn't match.
