### ISSUE TITLE
Crash on exit

### ISSUE THREAD

**Issue by ScreenDream** [still-scene/t3#116]
I see a crash each time I exit t3 in every version I ever tried, 3.3 standalone as well as all latest dev builds.
The only instance it does not crash is when I open t3 and instantly close it again without touching any operators. As soon as I show any preview of an operator, the crash on closing t3 happens.

**Please complete the following information):**
 - OS: Windows 10, latest, all updates installed.
 - Version: All tested versions, standalone 3.3 and latest dev compile.
 - Graphics card and resolution: Nvidia GTX 840M, 2GB RAM, 1920x1080, latest drivers.
 - Acer Laptop, i7 4720HQ @ 2.6 GHz, 16GB RAM.

I added a screenshot of the point where the debugger jumps to.
If you need more information, please let me know.

![CrashOnExitDebug](https://user-images.githubusercontent.com/113698935/191049119-cf5ee88e-446e-4cc5-ae03-d06ec6443739.jpg)

**Comment by pixtur** [comment]
Thanks for reporting. 

We're aware of this issue and already spent some time looking into this issue. Sadly a solution is not straight forward.
But I completely agree that this is annoying and needs to be fixed.
