### ISSUE TITLE
[DampVec2] and [DampVec3]

### ISSUE THREAD

**Issue by pixtur** [still-scene/t3#121]
It would be great if [Damp] would be available for vector types.

**Comment by VeissieV** [comment]
How do you mean? I made a type that applies the same dampening to XYZ and another that allows for independent damping for each.

<img width="1263" alt="t3_PSkLaawyqa" src="https://user-images.githubusercontent.com/26267774/191630326-f7f48a0f-7a05-4ebe-b115-a7111f37d20a.png">

**Comment by pixtur** [comment]
Yes. Precisely that.  But I would do this in c#. Duplicating the [Damp] operator and converting the float parameter types to Vector2  and 3 should be straight forward. Building this from Operator components has an unnecessary performance overhead.

**Comment by pixtur** [comment]
Fixed in next release
