### ISSUE TITLE
Click on Windows menu toggles fullscreen

### ISSUE THREAD

**Issue by hollyhook** [still-scene/t3#126]
If you click on the Windoes menu, the first menu entry (Fullscreen) is activated.

![window](https://user-images.githubusercontent.com/9899825/191930872-000d4596-3133-428f-ad18-6929e0a07028.gif)

Likely only relevant for laptop user. The Windows menu is likely just too crowded, so it takes the full height of the screen and thus the first menu entry (Fullscreen) consumes the mouse release event.

**Comment by pixtur** [comment]
Oh! Thanks for reporting. I believe we should clean up the Windows menu!

**Comment by hollyhook** [comment]
When cleaning up the menu, you might consider to give the Parameter window also an entry, which is missing currently.
