### ISSUE TITLE
Value ladder should not behave as a multiplier but on precise digets of the edited value

### ISSUE THREAD

**Issue by pixtur** [still-scene/t3#127]
### Is your proposal related to a problem?

Currently when selecting 100 the virtual slider speed for 0.1 is multiplied by 100.
This behaviour is confusing because users expect to edit the current value by steps of +/- 100

**Comment by hollyhook** [comment]
Not sure if this has much to do with the original idea from here https://discord.com/channels/823853172619083816/986939795819339777/1022796998711185448 ? But nevertheless, I tried to record the behaviour of Max when changing a numbebr with the mouse

![MAX](https://user-images.githubusercontent.com/9899825/192087837-8c72a6d9-cf79-419c-a1d1-864f18caf6a1.gif)

Depending where on location in the number where the mouse down event was, the decimal are changed. Though the handling in Max is also far from perfect (there is no mouse pointer while dragging)

**Comment by pixtur** [comment]
@hollyhook: I'm not sure, if I agree with the Max implementation, but I can definitely see how this would be valuable. 
If we do this kind of interaction, it should definitely highlight the digit that will be affected by the mouse wheel.
