### ISSUE TITLE
Some Operators are in incorrect location or namespace

### ISSUE THREAD

**Issue by hollyhook** [still-scene/t3#133]
We made a list of operators which are potentially in the wrong folder or namespace, check out
https://github.com/still-scene/t3/wiki/Operator-in-incorrect-location-or-namespace

@pixtur please correct and/or complete where the right location would be

I'm happy to do the cleanup and create a PR

**Comment by pixtur** [comment]
@hollyhook I agree with all of you suggestions. Can you move them (either with the edit field in the parameter window or by dragging them with the symbol browser) to the correct locations and submit a pull request?

**Comment by hollyhook** [comment]
In some cases I don't know where to put the Operator.
@pixtur can you please look into the list and clarify the things marked with "?"

**Comment by pixtur** [comment]
Ups. Just did so!

**Comment by hollyhook** [comment]
done
