### ISSUE TITLE
Params write outside Operator box

### ISSUE THREAD

**Issue by hollyhook** [still-scene/t3#150]
**Describe the bug**
Parameter values of operators are sometimes visible outside the operator box

**Please complete the following information):**
 - OS: Win11
 - Version: ad473fb
 - Graphics card and resolution RTX3080 Laptop

**To Reproduce**
1. Open for instance [IterateListExample], or any other operators with params
2. Change zoom

**Expected behavior**
Text ends where the box ends

**Screenshots**
![image](https://user-images.githubusercontent.com/9899825/192232868-e3289015-5123-43e0-8a24-80441729dd7b.png)

**Comment by pixtur** [comment]
Yes. This glitch looks very unpleasing.
Fixed.

**Comment by pixtur** [comment]
Fixed in next release
