### ISSUE TITLE
Sometimes operator jumps on mouse drag

### ISSUE THREAD

**Issue by hollyhook** [still-scene/t3#152]
This is a way to reproduce it, a bit tricky but 100% reproducable

1) have a single operator outside of the current view
2) adjust view (f)
3) drag the operator 
    -> it gets duplicated, both are moving while dragging
4) release mouse, it is back to only 1 operator
5) try again to drag the op by clicking
   -> jumps on click

![evade2](https://user-images.githubusercontent.com/9899825/192367262-aa17ef8e-8d4a-4914-a2af-ebddd4fa48f1.gif)

Win 11 , version a8d06ae, Geforce RTX 3080.

**Comment by pixtur** [comment]
I thought I fixed this issue with https://github.com/still-scene/t3/commit/321e58d08a8ba49a2f2c91607660cbef285b6988

booo

**Comment by pixtur** [comment]
Can you confirm if this can still reproduced with v3.4?
I tried to but wasn't able to.

**Comment by hollyhook** [comment]
Still reproducible

**Comment by pixtur** [comment]
Thanks again for testing. I could finally reproduce and fix the issue.
