### ISSUE TITLE
Fix live preview thumbnail rendering

### ISSUE THREAD

**Issue by sense-amr** [still-scene/t3#153]
During my time navigating people through tooll3 , i have found that this feature being on by default .. causes confusion rather than provides a useful function.. i would propose that it be turned off by default in order to remove potential first user confusion with getting to grips with the tooll3 interface.. 

Users can always turn it back on IF they want to use it ..

**Comment by hollyhook** [comment]
I find it usefull, but it depends on the operator. For texture like operators it is indeed confusing because it shows the top left corner, which is often just empty

**Comment by sense-amr** [comment]
yeh you can always turn it on again .. but i think by default on especially when i have navigated over 100 people to use Tooll from the very beginning .. its not a help at all ..

**Comment by sense-amr** [comment]
Truthfully .. it shows nothing .. of the real usefulness of the operator .. for example if its a Texture operator you will see only a small undefined part of the image.. 
![image](https://user-images.githubusercontent.com/1504019/192481309-bb693387-a31e-44ee-aa94-001bd0a9cdac.png)

if its a display of say a AnimValue it will only show the small amount of the display .. again .. there are other ways of monitoring any data in Tooll and both of them are much better .. 

for example rolling over the cable of a connected object 
![image](https://user-images.githubusercontent.com/1504019/192481018-eef1d966-02b5-4dff-8ac1-4c339780ea94.png)


and if you REALLY Want to monitor things properly .. you would be best advised to open a New Output window and pin that with the information from the operator you want to see.. 

![image](https://user-images.githubusercontent.com/1504019/192481565-6ffdfd7f-78c7-466f-9816-2a190235d788.png)

Interestingly it also seemed to STOP you from viewing the output from the output window .. when you roll over it WITH hover on ..

https://user-images.githubusercontent.com/1504019/192482234-2df4ebb6-a4ba-4e9e-9075-df9f10cacfcf.mp4

**Comment by pixtur** [comment]
It should be fixed instead of deactivated.

This is also related to: https://github.com/still-scene/t3/issues/139

**Comment by pixtur** [comment]
Fixed in next release
