### ISSUE TITLE
Renaming operator not working

### ISSUE THREAD

**Issue by hollyhook** [still-scene/t3#154]
1) Right click on operator
2) Select Rename from context menu
3) Start typing for the new name
  -> either nothing happens or some unexpected scrolling

Keystrokes seems to interfere with commands (eg ASDW for scrolling etc)

version latest dev 0fdd87e

**Comment by pixtur** [comment]
Should be fixed.

**Comment by hollyhook** [comment]
The fix wasn't planned for 3.4, it is supposed to be fixed in 3.5

**Comment by pixtur** [comment]
Well spotted! The behavior is different between using the Return-key shortcut and the context menu.
I'm looking into that.
