### ISSUE TITLE
Layout of settings window should be improved

### ISSUE THREAD

**Issue by pixtur** [still-scene/t3#156]
The current layout is confusing and hard to read:

We should...

- remove obsolete options and debug output
- switch to left sided labels 

![image](https://user-images.githubusercontent.com/1732545/192649562-43b7ac86-23f4-4990-9ebb-0eaf018ff757.png)

**Comment by domportera** [comment]
Does this look like I'm on the right track?

![image](https://user-images.githubusercontent.com/6530600/193446329-9989d242-3124-4b81-b081-83f2c026cba0.png)

**Comment by pixtur** [comment]
Nice!

Some comments:
- Are you using the `CustomComponents.FloatValueEdit()` ? You can check how this is used in `RenderVideoWindow.cs`.
- The Checkbox should stay on the left side. (I have a kind of trauma on that topic :) )
