### ISSUE TITLE
AUDIO Soundtrack

### ISSUE THREAD

**Issue by sense-amr** [still-scene/t3#17]
Audio Soundtrack now no longer updates when file changed.. 
Update option is not present in newest build of master ..
The only way i found to load a new soundtrack file is to rebuild

**Comment by pixtur** [comment]
We added buttons to Update or Remove soundtracks to the playback settings in v3.2.1

**Comment by sense-amr** [comment]
hmm i dont see any update or remove button ? and im sure im using the latest .. as it does have your resynch threshold addition ... 
![image](https://user-images.githubusercontent.com/1504019/174877331-a5e47365-27ec-4cc7-b6c0-56c27a3333de.png)

**Comment by pixtur** [comment]
I'm sorry. It's still on the dev branch and has not been merged to master:

![image](https://user-images.githubusercontent.com/1732545/175094826-21c618fe-834e-4d90-99c9-d3622c81ac7e.png)

**Comment by sense-amr** [comment]
ahh yes thats ok just when you said it was merged into 3.2.1 i thought i was missing something somewhere i still havent tried any of the dev branches.. id have to look into how to do it in fork
