### ISSUE TITLE
AUDIO Muting Mutes ALL system audio

### ISSUE THREAD

**Issue by sense-amr** [still-scene/t3#18]
When activating the Mute function from the timeline panel for Audio .. ALL System audio is affected...
![MuteMutes ALLSysAudio](https://user-images.githubusercontent.com/1504019/174530716-539c822a-a196-4a00-8373-87c852e293ed.jpg)

**Comment by pixtur** [comment]
Good catch! 
We will address this issue in the next release.

**Comment by pixtur** [comment]
Fixed in v3.3.0
