### ISSUE TITLE
Grey corners while zooming

### ISSUE THREAD

**Issue by hollyhook** [still-scene/t3#182]
while zooming, the corners of some operators (e.g. [Remap]) are getting darker rectangles.

![corner](https://user-images.githubusercontent.com/9899825/193920847-ad51429f-9377-4e4a-b801-400a4678aaa8.gif)

On laptop, zoom by means of 2 finger on touchpad

**Comment by pixtur** [comment]
very interesting. Are you hold CTRL or any other modifier key?

**Comment by hollyhook** [comment]
No modifier, just 2 fingers moving away from each other

**Comment by pixtur** [comment]
This is so strange. I quickly looked into this, but the code doesn't really indicate anything that could trigger that:

```
            var editingUnlocked = ImGui.GetIO().KeyCtrl || _jogDialValue != null;
```            

I have to get access to a notebook to test this properly.

**Comment by sosias** [comment]
Trackpad on windows can scroll (two finger up and down) and zoom (two finger pinch)
the event for two finger scrolling is mouse wheel up / down
the event for two finger pinch is ctrl + mouse wheel up / down, that is why on zooming the ctrl key is registered

**Comment by pixtur** [comment]
Thanks for that explanation. I'm not really sure how to deal with this issue then. 
I'm closing the issue for now, but we can open it again later if can figure out how to distinguish this.
