### ISSUE TITLE
Random Value Jumps when using the ladder on parameters.

### ISSUE THREAD

**Issue by ScreenDream** [still-scene/t3#190]
We have an issue here that is a bit hard to show.
We get random value jumps when using the ladder to change parameters.
It is not consistent, but happens a lot here with a mouse, a laptop touchpad and a wacom pen, so seems independent of the input device.

Sometimes the ladder works as expected.
Sometimes the jumps are random and only happen occasionally.
Sometimes a certain value can't be changed effectively with the ladder at all, since on each click-drag to start changing the value, a random jump happens, like you start with 0.3 and on click-drag you suddenly get a value of -2.5 or 15.9 etc.

At times it's so bad, we have to revert to numerical input.

I tried to capture a gif, but it's really hard to see and only happens on some of the clicks. We weren't able to capture a situation yet where it happens all the time.

![RandomValueJumps](https://user-images.githubusercontent.com/113698935/194389121-512272d6-7512-4558-b4d4-f3c9691d5a88.gif)

This happens in all versions since the change of the ladder layout (which otherwise works very well for us). This report used the latest dev version on 6.10.2022 - post 3.4.

**Comment by pixtur** [comment]
Excellent report. What is your current frame rate?
I will look into this.

**Comment by ScreenDream** [comment]
My Laptop monitor does 60Hz, I guess my GFs Laptop also has 50 or 60Hz.
We don't have any gaming gear and the laptops are nothing fancy, so that framerate can't be changed.
I would have to check if it happens more when the project is getting heavier (happens fast on these laptops...).
But the "feeling" is, that the jump occurs even before one starts to drag, right away on the first click, but hard to tell really.

**Comment by pixtur** [comment]
should be fixed in next version
