### ISSUE TITLE
Feature Request: Export Player Windowed 

### ISSUE THREAD

**Issue by sense-amr** [still-scene/t3#193]
Considering the multiple use of T3 as a program to generate REAL TIME .. graphical content and also enable REAL TIME audioreaction .. it would be prudent to allow Windowed: true .. when running an export .. This will enable .. T3 made exports to be used in overlays such as those utilised in OBS..

![image](https://user-images.githubusercontent.com/1504019/194698017-3013148f-36da-4093-b573-1e5d91008a05.png)

**Comment by pixtur** [comment]
You can run the player in windowed mode with this parameter
```
player.exe --windowed
```

so you could create a file called `runSmall.bat` with the following content:

```
player.exe --windowed --width 128 --height 72
```


The player also supports to following parameters:
```
  --novsync     (Default: false) Disable vsync
  --width       (Default: 1920) Defines the width
  --height      (Default: 1080) Defines the height
  --windowed    (Default: false) Run in windowed mode
  --loop        (Default: false) Loops the demo
  --logging     (Default: true) Show log messages.
  --help        Display this help screen.
```
![image](https://user-images.githubusercontent.com/1732545/194730054-e6c061cd-398b-4cee-8224-56ce6cdaf864.png)

**Comment by sense-amr** [comment]
ahh ok so you fixed the icon problem cool

**Comment by sense-amr** [comment]
and not considering option to create this in the export for ease of use for the user? .. who might not be familiar with command lines

**Comment by pixtur** [comment]
We could include a bunch of bat files (for different resolutions, windowed etc.)
Added export options would be a bit out of scope for now.
