### ISSUE TITLE
Feature Request: Output Window Camera View reset.. 

### ISSUE THREAD

**Issue by sense-amr** [still-scene/t3#196]
When selecting an operator and moving around with the output view camera it is easy to potentially mess up the placement of something in the scene.. 

Also the rendertaget does not seem to update with this view.. 

It would be excellent to have a way to reset the "Camera" view in the output window .. to a default setting..

Currently the only way of doing this is with making a second output window .. work around ..

example here shows.. 
drawlines has been "moved" around in the output window ..
![image](https://user-images.githubusercontent.com/1504019/195496295-21d86e4b-bc57-4e0d-a0cd-f3eebcf22fbe.png)

Rendertarget is not reflecting this change.. 

![image](https://user-images.githubusercontent.com/1504019/195496353-db946d9c-411d-4277-a494-83f5d6717fa3.png)

Workaround to get the original positioning of the camera view in the output window ..

![image](https://user-images.githubusercontent.com/1504019/195496471-a3a3d9b0-0288-449a-aaf1-ac062ebe61a7.png)

**Comment by pixtur** [comment]
A keyboard shortcut for this is pressing F-key.

Related:
- #148

**Comment by pixtur** [comment]
Feel free to reopen.

**Comment by sense-amr** [comment]
damn i looked around for existing issue as i thought there might be one .. sorry about that.. it was just that a user was experieincing it in the discord and i tried to find the solution .. only thing i could come up with is make a new output window ..

**Comment by pixtur** [comment]
No worries, that what questions are for.
