### ISSUE TITLE
runtime measurements overwrite window frame

### ISSUE THREAD

**Issue by hollyhook** [still-scene/t3#197]
rendering frame duration in main menu area overwrite the Graph window.

![ms](https://user-images.githubusercontent.com/9899825/195816013-e9453af9-291b-4366-b741-01cf409fcc4b.gif)

This is the default layout after freshly installing T3 on my laptop, i.e. now windows were moved. 

Might be on purpose, but IMO it looks not great

version 770e100

**Comment by pixtur** [comment]
Not on purpose. Fixed.
