### ISSUE TITLE
Version Display

### ISSUE THREAD

**Issue by sense-amr** [still-scene/t3#20]
I am very weary of adding too many feature requests .. but i do think it would be very useful to have a Version display somewhere .. in T3
*Feature Request

**Comment by pixtur** [comment]
I completely agree. Currently you can see the version in window title bar. But it wouldn't hurt to add an about popup and also add the current version to the console log.

**Comment by sense-amr** [comment]
yeh i made this issue first then i saw the version number in the top of window .. and i thought sorry stupid for me to say it ..cos you already did actually take care of it!

**Comment by pixtur** [comment]
No worries. Always better to ask questions!

**Comment by pixtur** [comment]
Closed with v4.0
