### ISSUE TITLE
Docking a window can stop Evaluation 

### ISSUE THREAD

**Issue by hollyhook** [still-scene/t3#206]
Using the version with the new window docking (revision 79f4fa1 on dev)

When dragging a window to the Output window in order to have it as a extra tab, the evaluation stops.

Evaluation runs again on taking the window away from Output.

![stop](https://user-images.githubusercontent.com/9899825/196052625-d14d4b72-ad29-4f27-8bca-2b7aba295cd6.gif)

**Comment by pixtur** [comment]
This is be design. Only visible output windows are processed (evaluated) and only evaluated parts of the graph are being updated.
Is there a specific use case you need updating something that is not being rendered? Maybe sending Midi/Osc signals that don't need visual output?

**Comment by hollyhook** [comment]
aww, got it. closing the issue.
