### ISSUE TITLE
Entering operator fails with parameters window closed

### ISSUE THREAD

**Issue by WilliUreta** [still-scene/t3#21]
**Describe the bug**
Double clicking inside an operator with the parameters tab closed doesn't let you enter it.

**Please complete the following information):**
 - OS: Win 10
 - Version: 21H2
 - Graphics card and resolution: gt740 1080p

**To Reproduce**
1. Close Parameter window
2. Double click an operator to get inside it
3. First you see the output then a black box.

**Expected behavior**
You can enter inside an operator regardless of the windows open

**Screenshots**
![image](https://user-images.githubusercontent.com/62305530/175113240-f65996fc-17ff-47b8-92e7-a6a41064587b.png)

**Additional context**

**Comment by pixtur** [comment]
Thanks for reporting.
This a side effect of Graph above content-mode. I will fix this with an an update how the parameter popup is shown in this mode.
Until then you can hold Shift while double clicking as a work around.
