### ISSUE TITLE
Enhancement request: Add remove functionality to gradient selectors

### ISSUE THREAD

**Issue by WilliUreta** [still-scene/t3#22]
It would be really cool to remove the selectors from the gradient picker. Something along the lines: 
![image](https://user-images.githubusercontent.com/62305530/175115376-eff4442a-3261-43fc-80a5-79512bd1f5db.png)

Very cool project. Opensourcing the likes of Touchdesigner!

**Comment by pixtur** [comment]
You can remove handles by dragging them out of the gradient:
![Animation](https://user-images.githubusercontent.com/1732545/175122902-c93b0dd5-1845-4085-96ba-9ff3691bdc34.gif)

But having a remove there is also an interesting idea...
