### ISSUE TITLE
Creating a new project makes tooll3 crashes on next startup

### ISSUE THREAD

**Issue by star-333** [still-scene/t3#234]
**Description**
Cannot create a new empty project without tooll3 crashing the next time it is started

**System info**
 - OS: Windows 11 Family 
 - Version: Version 10.0.22621 Build 22621
 - Graphics Card: AMD Ryzen 7 5800H / NVIDIA Geforce RTX 3060 Laptop

1. Create a new empty project
2. Close tooll3
3. Start tooll3
4. tooll3 crashes

**Screenshots**
![image](https://user-images.githubusercontent.com/116896120/225582001-cf6300f4-643c-422d-99cf-bff3bf3b1b99.png)

**Comment by pixtur** [comment]
Did you start "StartT3.exe" (correct) or "Editor.exe" (not correct)?

**Comment by star-333** [comment]
"Editor.exe". "StartT3.exe" works 👍

**Comment by pixtur** [comment]
Awesome that it now works. I will close the issue.
