### ISSUE TITLE
SharpDX.SharpDXException

### ISSUE THREAD

**Issue by danielvw** [still-scene/t3#238]
I downloaded the latest Tooll3 version (3.5.1) and .net After starting the StarT3.exe I got the following error message:

![Screenshot 2023-03-23 133418](https://user-images.githubusercontent.com/2211714/227239945-3fee8b64-93c0-4e63-8fc3-d747e67381d7.png)

userSettings.json doesn't exist yet
projectSettings,json doesn't exist yet
SharpDX.SharpDXException ...

 - OS: Windows 11 Pro
 - Version: 22H2
 - Graphics card and resolution: Nvidia Geforce GTX 3090 TI

**Comment by pixtur** [comment]
Interesting. Not really sure what's going on here. Are you sure you have .net installed like description in the installation notes : https://github.com/still-scene/t3/wiki/Installation

**Comment by pixtur** [comment]
https://github.com/sharpdx/SharpDX/issues/495

I'm very sure this is related by missing graphics diagnostics tools. 
Please check the link in the installation guide posted above.

**Comment by danielvw** [comment]
You were right! The graphics tools are not installed by default onWindows 11. I followed this guide and it works: https://allthings.how/how-to-install-and-use-directx-graphics-tools-on-windows-11/
