### ISSUE TITLE
Export as video

### ISSUE THREAD

**Issue by thargal** [still-scene/t3#24]
Hi, sorry for this stupid question, but how to export a video as a file (avi, mov, etc)
Kind regards.

**Comment by pixtur** [comment]
This features is on the roadmap: https://github.com/still-scene/t3/issues/16

**Comment by sonnyobrien** [comment]
its completed, but how do you actually export video now?

**Comment by pixtur** [comment]
1. Start tixl
2. Select a video operator (e.g. SubdivisionStretch)
3. Open Window -> Render To Files
4. Click Render
