### ISSUE TITLE
Feature Request: Operator BlendTexture

### ISSUE THREAD

**Issue by sense-amr** [still-scene/t3#241]
It would be most useful to have a [BlendTexture] operator  just the same as [Picktexture] but with Blend capability on the index?
i guess its just a matter of making the index a float instead of an int?
and adding it as a Blend Parameter.. 

In fact it could be incorporated directly into the existing Picktexture.. and just use  a factor of 0 for NO blend at all.. between picked textures?.. or a tick option for "blending" on or something like that enabling the Index to be a float value instead of int .. allowing the "blend" between the textures..

**Comment by pixtur** [comment]
This will be available in the upcoming release 3.6.
