### ISSUE TITLE
Bug: Debug Properties incorrect working directory from clone 

### ISSUE THREAD

**Issue by sense-amr** [still-scene/t3#242]
![image](https://user-images.githubusercontent.com/1504019/227993449-80aed24a-2405-4133-b55b-bda17f2b1476.png)

should be  

![image](https://user-images.githubusercontent.com/1504019/227993992-9c3c5746-ae38-4533-8ef3-e450408ab319.png)

this default error setting for the working directory causes extra complexity in explaining how to go about building in an IDE .. 

Can we please set the default of the project to ..

**Comment by sense-amr** [comment]
can this even be fixed in a .sln config ? i looked around but i dont see anything with ```..``` in it .. i guess its in some code.. for not pointing to root..

**Comment by pixtur** [comment]
Should be fixed with 764a702533b63561b3954ecfe68c77df3f34ad3d
