### ISSUE TITLE
The undo/redo feature is inconsistent

### ISSUE THREAD

**Issue by domportera** [still-scene/t3#246]
### Is your proposal related to a problem?

The undo UX is lacking.

### Describe the solution you'd like

The "model" should be read-only, and all actions performed by users (modifications of the "model) should be made through `Command`s. 

After this, `Command` implementations can be refactored such that Undo/Redo must be supported for all commands.

### Additional context

"I believe currently the WORST part of of T3 is undo."
- *pixtur, 2023*

**Comment by pixtur** [comment]
I fixed a number of undo/redo related issues over the last couple of days. So the situation should have been improved a lot. After looking that the diversity of code I think that the above method is not feasible or at least out of scope for now.

So I'm closing this issue. We can reopen it later.
