### ISSUE TITLE
AudioReaction with Pulse output is behaving unexpectable.

### ISSUE THREAD

**Issue by gad-ass** [still-scene/t3#258]
**Describe the bug**
After importing audio to playback, adding AudioReaction with **pulse** setting in beginning it's working correctly, but after scrubbing the timeline it's starting to lag. 

**Please complete the following information):**
 - OS: Windows 11
 - Version: v3.6.0 (github release)
 - Graphics card and resolution RTX4090 

**To Reproduce**
1. Add audio in Playback settings
2. Add AudioReaction (Output is on Pulse by default)
3. Setup parameters using control+mouse
4. Start Playback
5. Scrub on timeline while sound is playing.
6. Output is no longer working correctly, until you wait some time, or copy -> paste same node alongside.

**Expected behavior**
Output value should work like before scrubbing. 

**Screenshots**

https://github.com/still-scene/t3/assets/32915902/3eb965c5-79e6-49d4-ad6a-f4538288f692

**Comment by domportera** [comment]
@sense-amr pls feel free to add your insights :)

**Comment by gad-ass** [comment]
Same with Count output.

https://github.com/still-scene/t3/assets/32915902/d828951f-8910-43f5-a673-5cab9fdba6bb

**Comment by sense-amr** [comment]
> Same with Count output.
> 
>  broken_count.mp4

please try this with External Audio detection also

**Comment by gad-ass** [comment]
https://github.com/still-scene/t3/assets/32915902/0968bc0d-d12d-4336-a9a3-95da2fff8dfc

**Comment by sense-amr** [comment]
yep thats the one :) ..

**Comment by Athsanmles97** [comment]
How to add Chinese font inside？

**Comment by Athsanmles97** [comment]
How to add Chinese font inside？   I tried u8 and checked a lot of information, but I always reported errors in the process of writing

**Comment by domportera** [comment]
> How to add Chinese font inside？   I tried u8 and checked a lot of information, but I always reported errors in the process of writing

Sorry but this isn't relevant to this issue. I created a new one for you

**Comment by pixtur** [comment]
Thanks for reporting. This issue has been fixed in the upcoming release.
