### ISSUE TITLE
Export Player Not playing content properly 

### ISSUE THREAD

**Issue by sense-amr** [still-scene/t3#27]
A couple of things here.. 

Procedure was as advised create an upper level symbol from combining with Out Rendertarget.. object selected.. 
Attempt to Export as executable 

![image](https://user-images.githubusercontent.com/1504019/175367922-43fb6604-7791-4222-a129-50759fe8cc2c.png)

inside symbol .. 

![image](https://user-images.githubusercontent.com/1504019/175368015-ca7ad88a-975c-4f80-8fc8-3c0e85815f8a.png)

Managed to catch a screen capture of this .. 

![image](https://user-images.githubusercontent.com/1504019/175368208-c56b1cc5-d8f9-4ef1-983c-8c11996bbbeb.png)

Player,exe WAS created.. sucessfully..

![image](https://user-images.githubusercontent.com/1504019/175368279-cb9449b7-876f-4ebe-95d4-b6102b18e257.png)

I know it might take microseconds to create the Executable but is it possible to provide a dialogue when this is done sucessfully.. and a dialogue to the location it can be found ? .. 
\t3\Export

**Comment by pixtur** [comment]
I added final log messages (successful or failed) that will be visible in the upper right corner.
