### ISSUE TITLE
Shake to remove operator connections is not working

### ISSUE THREAD

**Issue by hollyhook** [still-scene/t3#34]
Shaking is not having any effect on my Windows 11 PC.

Analysis:

in class [ShakeDetector ](https://github.com/still-scene/t3/blob/5f048bef1908fe9c0d876e3eeeba468e17d326f2/T3/Gui/Graph/Interaction/SelectableNodeMovement.cs#L506)

while dragging, the function TestDragForShake(Vector2 mousePosition) is called permanently, also when not moving the mouse, or no movement detected. So the queue Directions is filled with almost only 0 and barely any other value. Thus a detection in direction changes fails, because non-zero dx values fall out of the queue.

I fixed it by moving the statement [Directions.Add(dx);](https://github.com/still-scene/t3/blob/5f048bef1908fe9c0d876e3eeeba468e17d326f2/T3/Gui/Graph/Interaction/SelectableNodeMovement.cs#L517) 3 lines up, preventing 0 values in the queue.

Unfortunately the fix didn't solve the issue for sense.

**Comment by sense-amr** [comment]
Its Also not working for me EVER on windows 10 @pixtur  !

**Comment by pixtur** [comment]
Thanks for this report. I reduced the sensitivity threshold so the gesture (shaking from left to right 3 times) should now be easier.

**Comment by hollyhook** [comment]
We identified the cause of the issue as 
1) there is a mouse position update per frame
2) the frame rate of 300Hz on my laptop fills the queue `Directions` very quickly, so that it is too short.

Identified fix is to change this line https://github.com/still-scene/t3/blob/5f048bef1908fe9c0d876e3eeeba468e17d326f2/T3/Gui/Graph/Interaction/SelectableNodeMovement.cs#L522 to 

````
if (Directions.Count > QueueLength * (1 / 60f) / Playback.LastFrameDuration)
````
Now it basically works, but I'm still under the impression that it sometimes fails. Can we re-open the issue for the time being? I'd like to observe a little more.
