### ISSUE TITLE
Exporting an op with a soundtrack added causes error

### ISSUE THREAD

**Issue by MaxiWH** [still-scene/t3#37]
**Describe the bug**
Adding a soundtrack to an operator that previously exported to an executable without issue causes an error to be thrown when attempting to export again. This is running Tooll3 ([V.3.2.2](https://github.com/still-scene/t3/commit/5f048bef1908fe9c0d876e3eeeba468e17d326f2)) through Visual Studio 2022 (Version 17.0.2).

**Please complete the following information):**
 - OS: Windows 10
 - Version: 21H2
 - Graphics card and resolution: NVIDIA GeForce GTX 1070 - 1920 x 1080

**To Reproduce**
1. Clone the project from [this ](https://github.com/still-scene/t3/commit/5f048bef1908fe9c0d876e3eeeba468e17d326f2) commit and launch it through Visual Studio 
2. Create an operator and prepare it for exporting following the instructions [here](https://github.com/still-scene/t3/wiki/export-executables)
3. Add a soundtrack to your operator
4. Right click your operator and choose *Export*
5. An error will occur reading something similar to this: `Error exporting resource 'E:\Music\Song.mp3' : 'The filename, directory name, or volume label syntax is incorrect. : 'D:\Program Files\t3\Export\E:\Music"`

**Expected behaviour**
The expected behaviour is to have the operator successfully export as it did before adding the soundtrack.

**Screenshots**
Here's a screenshot of the error thrown in the console within Tooll3
![bild](https://user-images.githubusercontent.com/72453520/176258215-db53c717-ca4b-4da7-bed8-bf88a57c0ec6.png)

**Additional context**
Here is the operator I used to re-create the issue a second time (without the soundtrack added)
[WavesNDots.zip](https://github.com/still-scene/t3/files/9003929/WavesNDots.zip)

**Comment by MaxiWH** [comment]
True, the export was actually successful even though this error was thrown.
The error is also avoided if the file for the soundtrack is placed within the `t3\Resources` folder. It only appears if the selected soundtrack resides outside the `t3\Resources` folder

**Comment by pixtur** [comment]
We added a warning if soundtrack is not within the `Resources\` directory and prevent a crash.
