### ISSUE TITLE
RadialGPoints: Not possible to create different values for Count

### ISSUE THREAD

**Issue by Gaspode8** [still-scene/t3#39]
**Describe the bug**
It's not possible to have more than one different value for "Count" in keyframe-animation.

**Please complete the following information):**
 - OS: win
 - Version: 3.2.2

**To Reproduce**
1. Create a RadialGPoint-Op
2. Type any number in Count-parameter
3. Click on the Keyframe-button to the left
4. Create another keyframe in the timeline
5. Change the value of Count
6. The value snaps back to the first value created under 2

**Expected behavior**
To have different values in the timeline.

**Additional context**
If you change the value while the timeline is running, the new values will be recorded correct. But if you try to change the value afterwards it will snap back too.

**Comment by pixtur** [comment]
Yes. integer values can't be animated with interpolation.  This is by design because be the jump points would not be predictable.
As a work around you can use an animated [FloatToInt] operator and connect it's output to the .Count parameter.
