### ISSUE TITLE
SoundTrack Frequency-span Analyzer

### ISSUE THREAD

**Issue by MaxiWH** [still-scene/t3#41]
**Feature Request**
A node which has a set of (3-5?) float outputs, each one representing the level of a certain frequency span from the soundtrack. Each output has an associated set of min and max frequency values. For more adjustable behaviour a drop-down could also be added for each output which changes how the level is determined (ex. *peak level in frequency span* or *average level in frequency span*)

A way to make it more intuitive would be to have the min and max values  be adjustable through points on a curve similar to how the bands applying low- & high-pass filtering in the equalizer (featured on the image below) is displayed ([MEqualizer](https://www.meldaproduction.com/MEqualizer))

![NVIDIA_Share_xTb2yYyP9h](https://user-images.githubusercontent.com/72453520/176584164-c2fbbffb-a598-4786-af9a-b4ba2f49fc3b.png)

**Comment by pixtur** [comment]
That's a very good idea. I was thinking about a similar solution for [AudioReaction]. Would you directly use the resulting value, or would you trigger something, if some kind of threshold is exceeded?

**Comment by sense-amr** [comment]
I think it would be nice to be able to set a spectral range .. to be able to be triggered on threshold .. so for example a selection of frequency between 30hz and 100hz to be triggered at threshold value reached.. Maybe even a selection for each of the most common bands used in audio mixing.. 

32 to 512Hz
512 to 2,048Hz
2,048 to 8,192Hz
8,192 to 16,384Hz

With a Q value or peak value for each ?

**Comment by pixtur** [comment]
This feature is partially available in v3.3.0 with the [AudioReaction] operator
