### ISSUE TITLE
New TimeClips should be created at current playback time

### ISSUE THREAD

**Issue by Gaspode8** [still-scene/t3#48]
**Describe the bug**
New TimeClips always appear at 0 on the timeline.

**Please complete the following information):**
 - OS: win
 - Version: 3.2.2

**To Reproduce**
1. Drag the timeline to the left
2. Create a timeclip

**Expected behavior**
The TimeClip should start at the current playback time.

**Comment by pixtur** [comment]
This feature will be available in v3.3.0
