### ISSUE TITLE
feature request: Allow creating a preset with default values 

### ISSUE THREAD

**Issue by hollyhook** [still-scene/t3#55]
Benefits

- Allow to morph other custom presets with the default one
- Quicker way to restore default after getting lost in morphing than reseting params individually

**Comment by hollyhook** [comment]
This is what you get when you try to save the defaults as preset
![image](https://user-images.githubusercontent.com/9899825/177039654-1ac5734b-da0c-493d-9334-eae88ac1b16b.png)

**Comment by pixtur** [comment]
Thanks for pointing this out. In fact I frequently have  the same issue and fall back to using the mouse-wheel to "change" value.
I will check if this warning could be safely ignored.
