### ISSUE TITLE
Visual effects are visible in the program but not in the player

### ISSUE THREAD

**Issue by Gaspode8** [still-scene/t3#56]
**Describe the bug**
Visual effects are visible in the program but not in the exported exe played with the player

**Please complete the following information):**
 - OS: win
 - Version: 3.2.2 (NOT standalone)
 - Graphics card: NVIDIA GeForce GTX 960 

**To Reproduce**
1. Copy and paste the example below
2. Export it and run in it with the player

Or create an Op-sequence of
Text->RenderTarget->Glow->Output

**Expected behavior**
In the example is a text with a glow. The text is visible, the glow isn't.

**Additional context**
Below is an example. Bt the problem occurs with other Ops like KochKaleidoskope, Blur etc.

**Comment by Gaspode8** [comment]
[
  {
    "Name": "Object",
    "Id": "fa8331cd-dfaa-4a03-b95e-fcad41f96cc1",
    "Inputs": [],
    "Children": [
      {
        "Id": "9609ff86-60f1-4cf5-8fd9-3bf2ce7f0796"/*Text*/,
        "SymbolId": "fd31d208-12fe-46bf-bfa3-101211f8f497",
        "InputValues": [],
        "Outputs": []
      },
      {
        "Id": "18ebf2f0-adb0-48b6-ad94-af3d0b80efb5"/*RenderTarget*/,
        "SymbolId": "f9fe78c5-43a6-48ae-8e8c-6cdbbc330dd1",
        "InputValues": [],
        "Outputs": []
      },
      {
        "Id": "ba95ff50-69eb-4bfc-86f9-7cb3255753e3"/*Glow*/,
        "SymbolId": "d392d4af-4c78-4f4a-bc3f-4c54c8c73538",
        "InputValues": [
          {
            "Id": "4927a3fc-87ff-44e7-88c0-499e3efcca55"/*GlowAmount*/,
            "Type": "System.Single",
            "Value": 0.55
          }
        ],
        "Outputs": []
      }
    ],
    "Connections": [
      {
        "SourceParentOrChildId": "9609ff86-60f1-4cf5-8fd9-3bf2ce7f0796",
        "SourceSlotId": "3f8b20a7-c8b8-45ab-86a1-0efcd927358e",
        "TargetParentOrChildId": "18ebf2f0-adb0-48b6-ad94-af3d0b80efb5",
        "TargetSlotId": "4da253b7-4953-439a-b03f-1d515a78bddf"
      },
      {
        "SourceParentOrChildId": "18ebf2f0-adb0-48b6-ad94-af3d0b80efb5",
        "SourceSlotId": "7a4c4feb-be2f-463e-96c6-cd9a6bad77a2",
        "TargetParentOrChildId": "ba95ff50-69eb-4bfc-86f9-7cb3255753e3",
        "TargetSlotId": "f6bdd487-c16e-4fb0-bfba-b3801f121314"
      }
    ]
  },
  {
    "Id": "fa8331cd-dfaa-4a03-b95e-fcad41f96cc1"/*Object*/,
    "InputUis": [],
    "SymbolChildUis": [
      {
        "ChildId": "9609ff86-60f1-4cf5-8fd9-3bf2ce7f0796"/*Text*/,
        "Size": {
          "X": 110.0,
          "Y": 23.0
        },
        "Position": {
          "X": 1190.3899,
          "Y": 364.9026
        }
      },
      {
        "ChildId": "18ebf2f0-adb0-48b6-ad94-af3d0b80efb5"/*RenderTarget*/,
        "Size": {
          "X": 110.0,
          "Y": 36.0
        },
        "Position": {
          "X": 1340.3899,
          "Y": 364.9026
        }
      },
      {
        "ChildId": "ba95ff50-69eb-4bfc-86f9-7cb3255753e3"/*Glow*/,
        "Size": {
          "X": 110.0,
          "Y": 36.0
        },
        "Position": {
          "X": 1490.3899,
          "Y": 364.9026
        }
      }
    ],
    "OutputUis": []
  }
]

**Comment by Gaspode8** [comment]
Log-file shows an error:

18:09:28.995 (Info): Failed to create pixel shader 'image-fx-bloom.hlsl'.
18:09:28.995 (Warning): Trying to issue draw call, but pixel and/or vertex shader are null.
18:09:28.996 (Error): Failed to compile shader 'image-fx-bloom.hlsl': Unable to find file
Using previous resource state.
18:09:28.996 (Info): Failed to create pixel shader 'image-fx-bloom.hlsl'.
18:09:28.996 (Warning): Trying to issue draw call, but pixel and/or vertex shader are null.

**Comment by Gaspode8** [comment]
'image-fx-bloom.hlsl' is missing under Resources/lib/img/fx

But inside Tooll the log-file shows no errors on export.

**Comment by Gaspode8** [comment]
With Toolls standalone-version the glow is exported correctly!
With the "normal" version it isn't. On my computer. :o)

**Comment by sense-amr** [comment]
yes all you need to do is copy the Player directory from the Visual Studio version to the Standalone root folder and export functionality should be available in Standalone.. preview 3.2.2

**Comment by Gaspode8** [comment]
This issue can be closed. It was a problem with changed internal Ops.
