### ISSUE TITLE
Force Player to start exe at timeline-position 0 after loading

### ISSUE THREAD

**Issue by Gaspode8** [still-scene/t3#59]
**Describe the bug**
Sometimes an exe starts a few seconds after timeline-position 0. This leads to cut off-problems when the soundtrack starts at 0.

**Please complete the following information):**
 - OS: win
 - Version: 3.2.2

**Expected behavior**
Start the exe at second 0 after loading.

**Comment by sense-amr** [comment]
i had a similar problem .. but at the other end the player was cutting off at the end 11 seconds early .. i think @pixtur is adressing this in player in general and has solved the problem for the next update of Standalone!

**Comment by pixtur** [comment]
I believe this should be fixed in the upcoming release.
