### ISSUE TITLE
Feature Request..Set Default Wasapi Device 

### ISSUE THREAD

**Issue by sense-amr** [still-scene/t3#61]
Having recently played around with Wasapi Audio in for processing in T3 .. it quickly became apparent that changing the device index "dynamically" is not well recieved by T3.. that the program doesnt like this kind of behaviour in hot switching devices .. which in fairness is TOTALLY understandable .. i mean we wouldnt expect to be able to change the graphics card on the fly .. with out some complaints and or real time reconfiguration.. 

With this in mind i came to the view that it would be a much better idea to perhaps set the "default wasapi device" and include this in maybe the soundtrack area.. where one can set the device for Wasapi that they are most commonly using and T3 would save this in its config .. so that each time the Wasapi function is called on .. T3 will know which device the user most commonly wants to use..

Of course if there is a NEED to change it .. the user could still use the Device index in AnalyzeSound operator to change the device .. although we are aware that this does NOT operate like a "hot swap" and a restart will be needed for it to take affect..Which to me lends even more credence to the idea that it should be a defined default setting...

Contribution from T3 user @nabr agreed with this .. and did some investigation in the config code.. and came up with this ..

@nabr
Currently, i just changed the following value according to my configuration, that gives me faster startup. https://github.com/still-scene/t3/blob/2750057c245b5f221df7eea1b60840856e6d1cca/Operators/Types/SoundInput.cs#L266

**Comment by drxian** [comment]
this is what i can do with audio in node in touch designer

I would think some similar functionality required.

Driver Driver - ⊞ - Select between DirectSound and ASIO drivers.

Device Device - ⊞ - A menu of available audio devices to receive input
from. Selecting default sets the audio device to that which is selected in
Windows Control Panel>Sounds and Audio Devices>Audio>Sound Recording.

Format Format - ⊞ - Selects mono, stereo, or multi-channel. Also determines
how many channels are created 1(mono) or 2(stereo left and stereo right)
etc.

Gain (dB) Gain - This parameter controls the volume of the channel before
it reaches the compressor. If the signal to be compressed is not in a
useful dynamic range, this parameter can be used to repair it.

**Comment by bmFicg** [comment]
nice

**Comment by pixtur** [comment]
The default wasapi device is now stored as part of `projectSettings.json` and also used by the executable player.
