### ISSUE TITLE
Feature Request: A stepped random shape for the [LFO]

### ISSUE THREAD

**Issue by antennatree** [still-scene/t3#63]
It would be very nice to have a random shape in the LFO Operator. It might be possible to create this with a combination of Ops, but having it built in to the LFO would be a "nice to have". Also a damping parameter so you could have stepped as well as sloping random oscillations.

**Comment by sense-amr** [comment]
yes great idea ... i would also like a Trigger input for the lfo ..

**Comment by antennatree** [comment]
[SampleCurve] gets pretty darn close to this feature (the response curve idea).

**Comment by pixtur** [comment]
Good idea. Took a slightly longer than I expected because I had to find a good hash function.
Available on the dev branch and in next release:

![image](https://user-images.githubusercontent.com/1732545/179086563-c034a154-218e-4492-95a1-5680590fa133.png)

**Comment by antennatree** [comment]
Brilliant, thanks!
