### ISSUE TITLE
Outputs can't be removed with Delete key

### ISSUE THREAD

**Issue by hollyhook** [still-scene/t3#67]
- Go into an operator
- Select any output by clicking with the mouse on it, so that it's highlighted
- try to remove it with Delete key 
 -> Selection vanishes but the output is not removed

Removing via context menu (Right click -> Delete) works as expected

**Comment by pixtur** [comment]
I can reproduce this issue. Thanks for reporting.

**Comment by domportera** [comment]
this was resolved in #171, can we close this?

**Comment by pixtur** [comment]
I checked and found some more issues related to this topic:
- Undo doesn't work
- Deleting output from code-ops caused exceptions -> Fixed
- Deleting doesn't work if output has code overrides like Transform-Gizmos
