### ISSUE TITLE
Annotation colors not saved.

### ISSUE THREAD

**Issue by antennatree** [still-scene/t3#69]
Annotation colors are not saved within an Operator. All default back to (1.0,1.0,1.0)...

**Comment by JinVeiss** [comment]
Colors seem to persist now in the latest dev branch, but I've noticed that all annotation boxes will move relatively to another location on the graph and all the text gets defaulted.

**Comment by antennatree** [comment]
Yeah, I've noticed this too. When you pop into an Operator and then come back out the Operator has moved.

**Comment by pixtur** [comment]
Should be fixed in upcoming version.
