### ISSUE TITLE
SequenceAnim (DEV) behaviour

### ISSUE THREAD

**Issue by sense-amr** [still-scene/t3#75]
introducing the Bias at say 0.500 and a rate of 0.33 makes the wrong values count backwards as it goes up when viewing the raw output of the SequenceAnim operator 

Example.. 
![X77Gx5AbGs](https://user-images.githubusercontent.com/1504019/181531328-f977681f-fc8f-4bb6-9d0c-2c5153708d46.gif)

In general no matter what you set min value to .. for example in this instance i set to 2 cos its my lowest value .. its still displaying incorrect values..
![UaBMtOAYAF](https://user-images.githubusercontent.com/1504019/181525433-273be72d-64d5-4627-a6a6-609f0fb6cfc7.gif)

Also query the idea of outputting float values on this device as the sequence values we must enter are int's not floats..

I understand this is a NEW operator and is still being developed so feel free to ignore my observations .. but i thought i'd make them just to let you know how my experience with this operator is ..

I would REALLY love to use it .. as intended..

**Comment by pixtur** [comment]
I can't reproduce this issue.
![image](https://user-images.githubusercontent.com/1732545/191588616-894dcd54-03ff-43a8-a635-75a34c3fd9c5.png)
