### ISSUE TITLE
PlayVideo node does not produce a texture

### ISSUE THREAD

**Issue by mfep** [still-scene/t3#76]
**Describe the bug**
- As said in the title, the PlayVideo node does not work.
- According to information to the developers, it's not yet implemented.
- This issue is created to track the developments on the PlayVideo node.

**Please complete the following information):**
 - OS: Windows 10
 - Version: 3.3.0
 - Graphics card and resolution: GTX 750, all resolutions 

**To Reproduce**
1. Create PlayVideo node
2. Set a path to a local video file
3. Start playback
4. Observe that no texture is outputted from the node

**Expected behavior**
PlayVideo node plays the loaded video as a texture output.

**Comment by HolgerFoerterer** [comment]
In the dev branch, PlayVideo now supports basic Microsoft MediaFoundation playback.
In addition, the operator PlayVideoClip can be used to move video clips around and change their speed.
