### ISSUE TITLE
Minimising T3 Window Makes everything disappear 

### ISSUE THREAD

**Issue by sense-amr** [still-scene/t3#8]
When minimising T3 window .. all information in the screen totally disappears.. 
The only way i have found to restore it is to use Load Layout .. 

![image](https://user-images.githubusercontent.com/1504019/164549863-52bafd17-937e-4c88-9b0f-f53404d80249.png)

**Comment by pixtur** [comment]
This should be fixed in v3.3.0

**Comment by sense-amr** [comment]
completely fixed all window handling issues :) danke!
