### ISSUE TITLE
BUG: Dev .. Render Sequence parameter window Size.. 

### ISSUE THREAD

**Issue by sense-amr** [still-scene/t3#86]
The Size of the ```Render Sequence``` parameter window is the length of the screen and cant be changed or resized.. 
![image](https://user-images.githubusercontent.com/1504019/187003150-4dc3397b-f8b2-46c7-8395-97a0ebd271a4.png)
Suggest to make the size of this window the same size as parameters or .. Variations ... etc to keep consistency in ui with the programme..

**Comment by pixtur** [comment]
Should be fixed in v3.4
