### ISSUE TITLE
[Bug?] Can't change opacity on DrawLinesBuildup with alpha

### ISSUE THREAD

**Issue by VeissieV** [still-scene/t3#99]
Thinking there may be something going on with the blend modes that may be causing this. I can only seem to get blend modes 3 and 4 to work with this op. Perhaps the alpha doesn't function as expected in these modes and we're missing modes for 0-2? Maybe they're not modes and BlendMod is something else.(not a typo)
![image](https://user-images.githubusercontent.com/26267774/189462263-c95aeb88-c18b-4bb9-a4e4-0b8f3f0c167f.png)

The description for this op could use a little update too.
Current:
Renders incomming points are growing strokes. The 
points' W attribute has the encode the U progress of 
the the extend of the strokes. 

Suggested:
Incoming points are rendered as growing strokes. 
The points' W attribute is encoded with the U progress of the extent of the strokes.

**Comment by pixtur** [comment]
I think [DrawLinesBuildup] is hasn't been tested well and is probably deprecated. 
I can have a look at this, but it definitely needs better documentation and touchup. Thanks for reporting.

**Comment by pixtur** [comment]
I improved the operator:
- added valid default parameters
- fixed the BlendMode selector
- added some documentation.

Ideally it should be used like this:

![image](https://user-images.githubusercontent.com/1732545/191583676-6c81f7d3-5b95-4c12-ace4-882860864210.png)

![image](https://user-images.githubusercontent.com/1732545/191584090-f9dbe43a-75bc-4969-93d1-df43ff62c03a.png)
